### ISSUE TITLE
base32.decode returns exactly same bytes from two different strings.

### ISSUE THREAD

**Issue by E5presso** [mdomke/python-ulid#31] opened 2024-08-20 06:30 UTC
Hello, I am currently using your ULID as the primary key (PK) for the database.

The reason I am reaching out is because while retrieving the database’s PK string using `ULID.from_str`, I encountered a PK collision. While debugging this issue, I discovered that `base32.decode` is converting different strings into the same binary value.

I suspect this may be due to a malfunction in the `decode_randomness` function.
Here is my test code.

```python3
from ulid import base32


def test_ulid_decode() -> None:
    first_sample = base32.decode("01J5PP33KAV586VA6296VXF0HU")
    second_sample = base32.decode("01J5PP33KAV586VA6296VXF0QZ")
    assert first_sample == second_sample # this must be failed but it actually passed.
```

**Comment by migonzalvar** [comment] 2024-09-12 17:31
I can't reproduce  this test case.

The ULID Spec in https://github.com/ulid/spec?tab=readme-ov-file#encoding says:

> Crockford's Base32 is used as shown. This alphabet excludes the letters I, L, O, and U to avoid confusion and abuse.
>
> ```
> 0123456789ABCDEFGHJKMNPQRSTVWXYZ
> ```

@E5presso the first string, `"01J5PP33KAV586VA6296VXF0HU"`, is not valid because it contains the letter `"U"`.

**Comment by mdomke** [comment] 2024-10-11 15:42
@E5presso If I'm trying to decode the value in `first_sample` I get a `ValueError` for the reasons pointed out by @migonzalvar 
```pycon
>>> from ulid import base32
>>> base32.decode("01J5PP33KAV586VA6296VXF0HU")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/martin.domke/Source/private/ulid/ulid/base32.py", line 198, in decode
    raise ValueError(f"Encoded ULID can only consist of letters in {ENCODE}.")
ValueError: Encoded ULID can only consist of letters in 0123456789ABCDEFGHJKMNPQRSTVWXYZ.
```
Is there maybe something else going on in your code? Did you solve the issue by now?

**Comment by mdomke** [comment] 2024-10-14 11:31
@E5presso I will close this issue for now. If there is any further evidence for a bug in the code, feel free to reopen it.

**Closed by mdomke** 2024-10-14 11:31 UTC
